-- CREATING THE TABLE 

DROP TABLE IF EXISTS retail_sales; 
CREATE TABLE retail_sales
		(
		transactions_id INT,
		sale_date DATE,
		sale_time TIME,
		customer_id INT,
		gender VARCHAR(15),
		age INT,
		category VARCHAR(20),
		quantiy INT,
		price_per_unit FLOAT,
		cogs FLOAT,
		total_sale FLOAT
		)	

---SHOW TABLE
SELECT * FROM retail_sales;

---detecting null values;
SELECT * FROM retail_sales
WHERE 
		transactions_id IS NULL 
		OR
		sale_date IS NULL 
		OR
		sale_time IS NULL 
		OR
		customer_id IS NULL 
		OR
		gender IS NULL 
		OR
		age IS NULL 
		OR
		category IS NULL 
		OR
		quantiy IS NULL 
		OR
		price_per_unit IS NULL 
		OR
		cogs IS NULL 
		OR
		total_sale IS NULL
		
;

--- DELETING NULL VALUES

delete from retail_sales
where 
transactions_id IS NULL 
		OR
		sale_date IS NULL 
		OR
		sale_time IS NULL 
		OR
		customer_id IS NULL 
		OR
		gender IS NULL 
		OR
		age IS NULL 
		OR
		category IS NULL 
		OR
		quantiy IS NULL 
		OR
		price_per_unit IS NULL 
		OR
		cogs IS NULL 
		OR
		total_sale IS NULL

--- data exploration 

--- total number of sales
select count(*) as total_sales from retail_sales;

--- how many customer we have ?
select count(distinct customer_id) as total_customer from retail_sales;

--- how many catagories we have ;
select distinct category  from retail_sales;

---data analysis and key problems and answers;
-- retrive all the sales made on '2022-11-05'

select  * from retail_sales 
where sale_date ='2022-11-05'

-- retrive all transactions where the category is 'clothing ' and the quantity is sold more than 4
--on the month of nov-2022

select  * 
from retail_sales 
where 
	category ='Clothing'
	and to_char(sale_date,'YYYY-MM') = '2022-11'
	and quantiy>=4;

---calculate total sale for each category?
select category,
sum(total_sale)as net_sale ,
count(*) as table_orders
from retail_sales
group by category;

---find the avg age of the customer who purchase item from 'beauty' category?
select category,round(AVG(age),2) from retail_sales
where category = 'Beauty'
group by category;

--find all the transaction where the total sales is greter than 1000;
select * from retail_sales
where total_sale>=1000;


--total number of transaction made by each gender in each category;
select gender,category,count(*) as "net sale" from retail_sales
group by gender,category
order by 2 desc;

-- calculate the avg sale for each month and find out selling month in each year;
select 
	extract (year from sale_date) as year,
	extract (month from sale_date) as month,
	avg(total_sale) as avg_Sale,
    RANK() OVER(
        PARTITION BY EXTRACT(YEAR FROM sale_date)
        ORDER BY AVG(total_sale) DESC
    )
from retail_sales
group by 1,2
order by 1,3 desc;

--highest avg selling
select year,month,avg_sale from 
	(select 
		extract (year from sale_date) as year,
		extract (month from sale_date) as month,
		avg(total_sale) as avg_Sale,
	    RANK() OVER(
	        PARTITION BY EXTRACT(YEAR FROM sale_date)
	        ORDER BY AVG(total_sale) DESC
	    )
	from retail_sales
	group by 1,2
	order by 1,3 desc) as t1
	where rank = 1

--find the top 5 customer based on the highest total sale
select 
	customer_id,
	sum(total_sale) total_sale
from retail_sales
group by customer_id 
order by 2 desc limit 5

---find the number of unique customer who purchase items from each category

select category,count(distinct customer_id) unique_customer  from retail_sales
group by 1;

--create each shift and number of orders (eg morning <=12, afternooon between 12 & 17,evening > 17)
with hourly_sale
as
(select *,
	case
		when extract(hour from sale_time) < 12 then 'Morning'
		when extract(hour from sale_time) between 12 and 17 then 'Afternoon'
		else 'evening'
	end as shift
from retail_sales
)
select 
	shift,
	count(*)as total_orders from hourly_sale
group by shift

--Find the total revenue generated by each gender.
select gender,sum(total_sale) as REVENUE from retail_sales
group by gender
--Find the total quantity sold for each category.
select category, sum(quantiy) as total_quntity 
from retail_sales
group by 1

-- Find the category that generated the highest total sales.
select category,sum(total_sale) as total_sale from retail_sales
group by 1
order by 1 desc
limit 1

-- Find the average total_sale for each gender.
select gender,round(avg(total_sale)::numeric,2) from retail_sales
group by 1

-- Find the number of transactions for each month of 2022.
select 
	extract (year from sale_date) as year,
	extract (month from sale_date) as month,
	count(transactions_id) as num_of_transactions
from retail_sales
where to_char(sale_date,'yyyy')='2022'
group by 1,2
order by 1;

--Find the total sales for each month of 2022 and sort them from highest to lowest.
select 
	extract(year from sale_date) as year,
	extract(month from sale_date) as month,
	sum(total_sale) total_sale
from retail_sales
where to_char(sale_date,'YYYY')='2022'
group by 1,2
order by 3 desc

--Find the top 5 transactions with the highest quantity sold.
select *,quantiy from retail_sales
order by quantiy desc
limit 5


---Find the customer who has spent the most money overall.
select customer_id ,sum(total_sale) total_spent
from retail_sales
group by 1
order by 2 desc
limit 1

-- Find the average age of customers for each gender
select gender,round(avg(age),2) from retail_sales
group by 1

-- Find customers who have made more than 5 transactions.
select customer_id,
count(distinct transactions_id)
from retail_sales
group by 1
having count(transactions_id)>5
order by 2 desc


--Find categories where the total sales are greater than 200,000.
select category,sum(total_sale)as TOTAL_SALE from retail_sales
group by 1
having sum(total_sale)>200000

-- Find the highest-selling transaction for each category.
select category,
max(transactions_id) from retail_sales
group by  1

--Find the top 3 customers in terms of total spending within each category.
with customer_spending as(select 
	customer_id,
	category,
	round(sum(total_sale)::numeric,2) as total_spent,
	RANK()
OVER(
    PARTITION BY category
    ORDER BY sum(total_sale)
)as spend_rank
from retail_sales
group by 1,2)

select customer_id,category,total_spent,spend_rank
from customer_spending 
where spend_rank <=3
order by 2,4

-- Find the percentage contribution of each category to the overall sales.
SELECT
    category,
    ROUND(SUM(total_sale)::numeric, 2) AS category_sales,
    ROUND((100 * SUM(total_sale) / SUM(SUM(total_sale)) OVER ())::numeric,2
    ) AS pct_of_total
FROM retail_sales
GROUP BY 1
ORDER BY 3 DESC;
-- Find the monthly sales trend and calculate the difference between each
WITH monthly_sales AS (
    SELECT
        DATE_TRUNC('month', sale_date)::date AS month,
        SUM(total_sale) AS monthly_sales
    FROM retail_sales
    GROUP BY 1
)
SELECT
    month,
    ROUND(monthly_sales::numeric, 2) AS monthly_sales,
    ROUND((monthly_sales - LAG(monthly_sales) OVER (ORDER BY month))::numeric, 2)
        AS diff_from_prev_month,
    ROUND(
        (100.0 * (monthly_sales - LAG(monthly_sales) OVER (ORDER BY month))
         / LAG(monthly_sales) OVER (ORDER BY month))::numeric,
        2
    ) AS pct_change
FROM monthly_sales
ORDER BY month;